version: '3'

services:

    app:
        build:
            context: ./resources/docker/8.1
            dockerfile: Dockerfile
            args:
#                WWWGROUP: '${WWWGROUP}'
                XDEBUG: '${SAIL_XDEBUG:-false}'
                XDEBUG_PORT: '${SAIL_XDEBUG_PORT:-9003}'
        image: michman-8.1/app
        ports:
            - '80:8000'
        volumes:
            - '.:/var/www/html'
        restart: unless-stopped
        depends_on:
            - redis
            - mysql

    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redis-data:/data'
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]

    mysql:
        image: 'mysql:8.0'
        platform: 'linux/x86_64'
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            APP_DATABASE: '${DB_DATABASE}'
            APP_USER: '${DB_USERNAME}'
            APP_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mysql-data:/var/lib/mysql'
            - './resources/docker/mysql/init.sh:/docker-entrypoint-initdb.d/init.sh'
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]

volumes:
    redis-data:
        driver: local
    mysql-data:
        driver: local
